# Generated by Django 2.1.15 on 2019-12-04 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191204_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qresponses',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
