# Generated by Django 2.1.15 on 2019-12-04 05:44

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191204_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qresponses',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='qresponses',
            name='response_array',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
